#include <instructions.h>
#include <cpu.h>



instruction instructions[0x100] = {
    //0X00
    [0x00] = {IN_NOP, AM_IMP},
    [0x01] = {IN_LD, AM_R_D16, RT_BC},
    [0x02] = {IN_LD, AM_MR_R, RT_BC,RT_A},
    [0x03] = {IN_INC, AM_R, RT_BC},
    [0x04] = {IN_INC,AM_R, RT_B},
    [0x05] = {IN_DEC,AM_R,RT_B},
    [0x06] = {IN_LD, AM_R_D8, RT_B},
    [0x07] = {IN_RLCA}, // IDK , MAYBE ITS FINE
    [0x08] = {IN_LD, AM_A16_R, RT_NONE,RT_SP},
    [0x09] = {IN_ADD, AM_R_R, RT_HL, RT_BC},
    [0x0A] = {IN_LD,AM_R_MR,RT_A,RT_BC},
    [0x0B] = {IN_DEC,AM_R,RT_BC},
    [0x0C] = {IN_INC, AM_R, RT_C},
    [0x0D] = {IN_DEC, AM_R, RT_C},
    [0x0E] = {IN_LD, AM_R_D8, RT_C},
    [0x0F] = {IN_RRCA},

    //0X10
    [0x10] = {IN_STOP},
    [0x11] = {IN_LD, AM_R_D16, RT_DE},
    [0x12] = {IN_LD, AM_MR_R, RT_DE,RT_A},
    [0x13] = {IN_INC, AM_R, RT_DE},
    [0x14] = {IN_INC,AM_R, RT_D},
    [0x15] = {IN_DEC,AM_R,RT_D},
    [0x16] = {IN_LD, AM_R_D8, RT_D},
    [0x17] = {IN_RLA},
    [0x18] = {IN_JR,AM_D8},
    [0x19] = {IN_ADD, AM_R_R, RT_HL, RT_DE},
    [0x1A] = {},
    [0x1B] = {},
    [0x1C] = {},
    [0x1D] = {},
    [0x1E] = {},
    [0x1F] = {},

    //0X20
    [0x20] = {IN_JR, AM_D8,RT_NONE, RT_NONE, CT_NZ},
    [0x21] = {IN_LD, AM_R_D16, RT_HL},
    [0x22] = {IN_LD, AM_HLI_R, RT_HL,RT_A},
    [0x23] = {IN_INC, AM_R, RT_HL},
    [0x24] = {IN_INC,AM_R, RT_H},
    [0x25] = {IN_DEC,AM_R,RT_H},
    [0x26] = {IN_LD, AM_R_D8, RT_H},
    [0x27] = {IN_DAA},
    [0x28] = {IN_JR, AM_D8, RT_NONE, RT_NONE, CT_Z},
    [0x29] = {IN_ADD, AM_R_R, RT_HL, RT_HL},
    [0x2A] = {},
    [0x2B] = {},
    [0x2C] = {},
    [0x2D] = {},
    [0x2E] = {},
    [0x2F] = {},

    //0X30
    [0x30] = {},
    [0x31] = {IN_LD, AM_R_D16, RT_SP},
    [0x32] = {IN_LD, AM_HLD_R, RT_HL,RT_A},
    [0x33] = {IN_INC, AM_R, RT_SP},
    [0x34] = {IN_INC,AM_R, RT_HL},
    [0x35] = {IN_DEC,AM_R,RT_HL},
    [0x36] = {IN_LD, AM_R_D8, RT_HL},
    [0x37] = {IN_SCF},
    [0x38] = {IN_JR,AM_D8,RT_NONE, RT_NONE,},
    [0x39] = {IN_ADD, AM_R_R, RT_HL, RT_SP},
    // [0x3A] = {},
    // [0x3B] = {},
    // [0x3C] = {},
    // [0x3D] = {},
    // [0x3E] = {},
    // [0x3F] = {},

    // //0X40
    // [0x40] = {},
    // [0x41] = {},
    // [0x42] = {},
    // [0x43] = {},
    // [0x44] = {},
    // [0x45] = {},
    // [0x46] = {},
    // [0x47] = {},
    // [0x48] = {},
    // [0x49] = {},
    // [0x4A] = {},
    // [0x4B] = {},
    // [0x4C] = {},
    // [0x4D] = {},
    // [0x4E] = {},
    // [0x4F] = {},

    // //0X50
    // [0x50] = {},
    // [0x51] = {},
    // [0x52] = {},
    // [0x53] = {},
    // [0x54] = {},
    // [0x55] = {},
    // [0x56] = {},
    // [0x57] = {},
    // [0x58] = {},
    // [0x59] = {},
    // [0x5A] = {},
    // [0x5B] = {},
    // [0x5C] = {},
    // [0x5D] = {},
    // [0x5E] = {},
    // [0x5F] = {},

    // //0X60
    // [0x60] = {},
    // [0x61] = {},
    // [0x62] = {},
    // [0x63] = {},
    // [0x64] = {},
    // [0x65] = {},
    // [0x66] = {},
    // [0x67] = {},
    // [0x68] = {},
    // [0x69] = {},
    // [0x6A] = {},
    // [0x6B] = {},
    // [0x6C] = {},
    // [0x6D] = {},
    // [0x6E] = {},
    // [0x6F] = {},

    // //0X70
    // [0x70] = {},
    // [0x71] = {},
    // [0x72] = {},
    // [0x73] = {},
    // [0x74] = {},
    // [0x75] = {},
    // [0x76] = {},
    // [0x77] = {},
    // [0x78] = {},
    // [0x79] = {},
    // [0x7A] = {},
    // [0x7B] = {},
    // [0x7C] = {},
    // [0x7D] = {},
    // [0x7E] = {},
    // [0x7F] = {},

    // //0X80
    // [0x80] = {},
    // [0x81] = {},
    // [0x82] = {},
    // [0x83] = {},
    // [0x84] = {},
    // [0x85] = {},
    // [0x86] = {},
    // [0x87] = {},
    // [0x88] = {},
    // [0x89] = {},
    // [0x8A] = {},
    // [0x8B] = {},
    // [0x8C] = {},
    // [0x8D] = {},
    // [0x8E] = {},
    // [0x8F] = {},

    // //0X90
    // [0x90] = {},
    // [0x91] = {},
    // [0x92] = {},
    // [0x93] = {},
    // [0x94] = {},
    // [0x95] = {},
    // [0x96] = {},
    // [0x97] = {},
    // [0x98] = {},
    // [0x99] = {},
    // [0x9A] = {},
    // [0x9B] = {},
    // [0x9C] = {},
    // [0x9D] = {},
    // [0x9E] = {},
    // [0x9F] = {},

    // //0XA0
    // [0xA0] = {},
    // [0xA1] = {},
    // [0xA2] = {},
    // [0xA3] = {},
    // [0xA4] = {},
    // [0xA5] = {},
    // [0xA6] = {},
    // [0xA7] = {},
    // [0xA8] = {},
    // [0xA9] = {},
    // [0xAA] = {},
    // [0xAB] = {},
    // [0xAC] = {},
    // [0xAD] = {},
    // [0xAE] = {},
    [0xAF] = {IN_XOR, AM_R, RT_A},

//     //0XB0
//     [0xB0] = {},
//     [0xB1] = {},
//     [0xB2] = {},
//     [0xB3] = {},
//     [0xB4] = {},
//     [0xB5] = {},
//     [0xB6] = {},
//     [0xB7] = {},
//     [0xB8] = {},
//     [0xB9] = {},
//     [0xBA] = {},
//     [0xBB] = {},
//     [0xBC] = {},
//     [0xBD] = {},
//     [0xBE] = {},
//     [0xBF] = {},


//    //0XC0
//     [0xC0] = {},
//     [0xC1] = {},
//     [0xC2] = {},
    [0xC3] = {IN_JP, AM_D16},
    // [0xC4] = {},
    // [0xC5] = {},
    // [0xC6] = {},
    // [0xC7] = {},
    // [0xC8] = {},
    // [0xC9] = {},
    // [0xCA] = {},
    // [0xCB] = {},
    // [0xCC] = {},
    // [0xCD] = {},
    // [0xCE] = {},
    // [0xCF] = {},

    // //0XD0   
    // [0xD0] = {},
    // [0xD1] = {},
    // [0xD2] = {},
    // [0xD3] = {},
    // [0xD4] = {},
    // [0xD5] = {},
    // [0xD6] = {},
    // [0xD7] = {},
    // [0xD8] = {},
    // [0xD9] = {},
    // [0xDA] = {},
    // [0xDB] = {},
    // [0xDC] = {},
    // [0xDD] = {},
    // [0xDE] = {},
    // [0xDF] = {},
    // //0XE0
    // [0xE0] = {},
    // [0xE1] = {},
    // [0xE2] = {},
    // [0xE3] = {},
    // [0xE4] = {},
    // [0xE5] = {},
    // [0xE6] = {},
    // [0xE7] = {},
    // [0xE8] = {},
    // [0xE9] = {},
    // [0xEA] = {},
    // [0xEB] = {},
    // [0xEC] = {},
    // [0xED] = {},
    // [0xEE] = {},
    // [0xEF] = {},

    // //0XF0
    // [0xF0] = {},
    // [0xF1] = {},
    // [0xF2] = {},
        [0xF3] = {IN_DI}
    // [0xF4] = {},
    // [0xF5] = {},
    // [0xF6] = {},
    // [0xF7] = {},
    // [0xF8] = {},
    // [0xF9] = {},
    // [0xFA] = {},
    // [0xFB] = {},
    // [0xFC] = {},
    // [0xFD] = {},
    // [0xFE] = {},
    // [0xFF] = {}

};

instruction *instruction_by_opcode(u8 opcode) {
    return &instructions[opcode];

}



char *inst_lookup[] = {
    "<NONE>",
    "NOP",
    "LD",
    "INC",
    "DEC",
    "RLCA",
    "ADD",
    "RRCA",
    "STOP",
    "RLA",
    "JR",
    "RRA",
    "DAA",
    "CPL",
    "SCF",
    "CCF",
    "HALT",
    "ADC",
    "SUB",
    "SBC",
    "AND",
    "XOR",
    "OR",
    "CP",
    "POP",
    "JP",
    "PUSH",
    "RET",
    "CB",
    "CALL",
    "RETI",
    "LDH",
    "JPHL",
    "DI",
    "EI",
    "RST",
    "IN_ERR",
    "IN_RLC", 
    "IN_RRC",
    "IN_RL", 
    "IN_RR",
    "IN_SLA", 
    "IN_SRA",
    "IN_SWAP", 
    "IN_SRL",
    "IN_BIT", 
    "IN_RES", 
    "IN_SET"
};

char *inst_name(in_type t) {
    return inst_lookup[t];
}
